# Generated by Django 2.2.5 on 2019-10-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191029_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amazon_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
